/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListResultOfCard,
} from '../models';
import {
    ListResultOfCardFromJSON,
    ListResultOfCardToJSON,
} from '../models';

/**
 * 
 */
export class CardsApi extends runtime.BaseAPI {

    /**
     * Lists the cards.
     */
    async cardsListRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListResultOfCard>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v2/Cards`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListResultOfCardFromJSON(jsonValue));
    }

    /**
     * Lists the cards.
     */
    async cardsList(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListResultOfCard> {
        const response = await this.cardsListRaw(initOverrides);
        return await response.value();
    }

}
