/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  TransferCreateRequest,
} from '../models';
import {
    TransferCreateRequestFromJSON,
    TransferCreateRequestToJSON,
} from '../models';

export interface TransfersCreateRequest {
    value: TransferCreateRequest;
}

/**
 * 
 */
export class TransfersApi extends runtime.BaseAPI {

    /**
     * This operation executes a transfer between two accounts.
     */
    async transfersCreateRaw(requestParameters: TransfersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters.value === null || requestParameters.value === undefined) {
            throw new runtime.RequiredError('value','Required parameter requestParameters.value was null or undefined when calling transfersCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v2/Transfers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TransferCreateRequestToJSON(requestParameters.value),
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * This operation executes a transfer between two accounts.
     */
    async transfersCreate(requestParameters: TransfersCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.transfersCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
