/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CardStatus {
    Unknown = 'Unknown',
    Active = 'Active',
    Inactive = 'Inactive',
    Renewal = 'Renewal',
    Deleted = 'Deleted',
    Blocked = 'Blocked'
}


export function CardStatusFromJSON(json: any): CardStatus {
    return CardStatusFromJSONTyped(json, false);
}

export function CardStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardStatus {
    return json as CardStatus;
}

export function CardStatusToJSON(value?: CardStatus | null): any {
    return value as any;
}

