/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Payment } from './Payment';
import {
    PaymentFromJSON,
    PaymentFromJSONTyped,
    PaymentToJSON,
} from './Payment';

/**
 * 
 * @export
 * @interface ListResultOfPayment
 */
export interface ListResultOfPayment {
    /**
     * 
     * @type {number}
     * @memberof ListResultOfPayment
     */
    availableItems: number;
    /**
     * 
     * @type {Array<Payment>}
     * @memberof ListResultOfPayment
     */
    items?: Array<Payment>;
}

/**
 * Check if a given object implements the ListResultOfPayment interface.
 */
export function instanceOfListResultOfPayment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "availableItems" in value;

    return isInstance;
}

export function ListResultOfPaymentFromJSON(json: any): ListResultOfPayment {
    return ListResultOfPaymentFromJSONTyped(json, false);
}

export function ListResultOfPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResultOfPayment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availableItems': json['availableItems'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(PaymentFromJSON)),
    };
}

export function ListResultOfPaymentToJSON(value?: ListResultOfPayment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availableItems': value.availableItems,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(PaymentToJSON)),
    };
}

