/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Account } from './Account';
import {
    AccountFromJSON,
    AccountFromJSONTyped,
    AccountToJSON,
} from './Account';

/**
 * 
 * @export
 * @interface ListResultOfAccount
 */
export interface ListResultOfAccount {
    /**
     * 
     * @type {number}
     * @memberof ListResultOfAccount
     */
    availableItems: number;
    /**
     * 
     * @type {Array<Account>}
     * @memberof ListResultOfAccount
     */
    items?: Array<Account>;
}

/**
 * Check if a given object implements the ListResultOfAccount interface.
 */
export function instanceOfListResultOfAccount(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "availableItems" in value;

    return isInstance;
}

export function ListResultOfAccountFromJSON(json: any): ListResultOfAccount {
    return ListResultOfAccountFromJSONTyped(json, false);
}

export function ListResultOfAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResultOfAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availableItems': json['availableItems'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(AccountFromJSON)),
    };
}

export function ListResultOfAccountToJSON(value?: ListResultOfAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availableItems': value.availableItems,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(AccountToJSON)),
    };
}

