/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StandingOrder } from './StandingOrder';
import {
    StandingOrderFromJSON,
    StandingOrderFromJSONTyped,
    StandingOrderToJSON,
} from './StandingOrder';

/**
 * 
 * @export
 * @interface ListResultOfStandingOrder
 */
export interface ListResultOfStandingOrder {
    /**
     * 
     * @type {number}
     * @memberof ListResultOfStandingOrder
     */
    availableItems: number;
    /**
     * 
     * @type {Array<StandingOrder>}
     * @memberof ListResultOfStandingOrder
     */
    items?: Array<StandingOrder>;
}

/**
 * Check if a given object implements the ListResultOfStandingOrder interface.
 */
export function instanceOfListResultOfStandingOrder(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "availableItems" in value;

    return isInstance;
}

export function ListResultOfStandingOrderFromJSON(json: any): ListResultOfStandingOrder {
    return ListResultOfStandingOrderFromJSONTyped(json, false);
}

export function ListResultOfStandingOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResultOfStandingOrder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availableItems': json['availableItems'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(StandingOrderFromJSON)),
    };
}

export function ListResultOfStandingOrderToJSON(value?: ListResultOfStandingOrder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availableItems': value.availableItems,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(StandingOrderToJSON)),
    };
}

