/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * 
 * @export
 * @interface ListResultOfTransaction
 */
export interface ListResultOfTransaction {
    /**
     * 
     * @type {number}
     * @memberof ListResultOfTransaction
     */
    availableItems: number;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof ListResultOfTransaction
     */
    items?: Array<Transaction>;
}

/**
 * Check if a given object implements the ListResultOfTransaction interface.
 */
export function instanceOfListResultOfTransaction(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "availableItems" in value;

    return isInstance;
}

export function ListResultOfTransactionFromJSON(json: any): ListResultOfTransaction {
    return ListResultOfTransactionFromJSONTyped(json, false);
}

export function ListResultOfTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResultOfTransaction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availableItems': json['availableItems'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(TransactionFromJSON)),
    };
}

export function ListResultOfTransactionToJSON(value?: ListResultOfTransaction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availableItems': value.availableItems,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(TransactionToJSON)),
    };
}

