/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MessageListItem } from './MessageListItem';
import {
    MessageListItemFromJSON,
    MessageListItemFromJSONTyped,
    MessageListItemToJSON,
} from './MessageListItem';

/**
 * 
 * @export
 * @interface ListResultOfMessageListItem
 */
export interface ListResultOfMessageListItem {
    /**
     * 
     * @type {number}
     * @memberof ListResultOfMessageListItem
     */
    availableItems: number;
    /**
     * 
     * @type {Array<MessageListItem>}
     * @memberof ListResultOfMessageListItem
     */
    items?: Array<MessageListItem>;
}

/**
 * Check if a given object implements the ListResultOfMessageListItem interface.
 */
export function instanceOfListResultOfMessageListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "availableItems" in value;

    return isInstance;
}

export function ListResultOfMessageListItemFromJSON(json: any): ListResultOfMessageListItem {
    return ListResultOfMessageListItemFromJSONTyped(json, false);
}

export function ListResultOfMessageListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResultOfMessageListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availableItems': json['availableItems'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(MessageListItemFromJSON)),
    };
}

export function ListResultOfMessageListItemToJSON(value?: ListResultOfMessageListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availableItems': value.availableItems,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(MessageListItemToJSON)),
    };
}

