/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Card } from './Card';
import {
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
} from './Card';

/**
 * 
 * @export
 * @interface ListResultOfCard
 */
export interface ListResultOfCard {
    /**
     * 
     * @type {number}
     * @memberof ListResultOfCard
     */
    availableItems: number;
    /**
     * 
     * @type {Array<Card>}
     * @memberof ListResultOfCard
     */
    items?: Array<Card>;
}

/**
 * Check if a given object implements the ListResultOfCard interface.
 */
export function instanceOfListResultOfCard(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "availableItems" in value;

    return isInstance;
}

export function ListResultOfCardFromJSON(json: any): ListResultOfCard {
    return ListResultOfCardFromJSONTyped(json, false);
}

export function ListResultOfCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResultOfCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'availableItems': json['availableItems'],
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(CardFromJSON)),
    };
}

export function ListResultOfCardToJSON(value?: ListResultOfCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'availableItems': value.availableItems,
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(CardToJSON)),
    };
}

