/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MailboxAttachment
 */
export interface MailboxAttachment {
    /**
     * 
     * @type {number}
     * @memberof MailboxAttachment
     */
    attachmentId: number;
    /**
     * 
     * @type {string}
     * @memberof MailboxAttachment
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MailboxAttachment
     */
    attachment?: string;
}

/**
 * Check if a given object implements the MailboxAttachment interface.
 */
export function instanceOfMailboxAttachment(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attachmentId" in value;

    return isInstance;
}

export function MailboxAttachmentFromJSON(json: any): MailboxAttachment {
    return MailboxAttachmentFromJSONTyped(json, false);
}

export function MailboxAttachmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): MailboxAttachment {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attachmentId': json['attachmentId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'attachment': !exists(json, 'attachment') ? undefined : json['attachment'],
    };
}

export function MailboxAttachmentToJSON(value?: MailboxAttachment | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attachmentId': value.attachmentId,
        'name': value.name,
        'attachment': value.attachment,
    };
}

