/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum NewStatusType {
    Stopped = 'Stopped',
    Reactivated = 'Reactivated',
    IgnoreLimit = 'IgnoreLimit'
}


export function NewStatusTypeFromJSON(json: any): NewStatusType {
    return NewStatusTypeFromJSONTyped(json, false);
}

export function NewStatusTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewStatusType {
    return json as NewStatusType;
}

export function NewStatusTypeToJSON(value?: NewStatusType | null): any {
    return value as any;
}

