/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ProductCode {
    DebitCard = 'DebitCard',
    DebitCardCl = 'DebitCardCL',
    CreditCard = 'CreditCard',
    CreditCardCl = 'CreditCardCL',
    DebitCardYouth = 'DebitCardYouth',
    DebitCardYouthCl = 'DebitCardYouthCL',
    X2XCard = 'X2XCard',
    X2XCardChild = 'X2XCardChild',
    X2XCardChildNet = 'X2XCardChildNet',
    ElectronCard = 'ElectronCard',
    Unknown = 'Unknown'
}


export function ProductCodeFromJSON(json: any): ProductCode {
    return ProductCodeFromJSONTyped(json, false);
}

export function ProductCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCode {
    return json as ProductCode;
}

export function ProductCodeToJSON(value?: ProductCode | null): any {
    return value as any;
}

