/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ReservationType {
    NotReservation = 'NotReservation',
    VisaReservation = 'VisaReservation',
    PurchaseReservation = 'PurchaseReservation',
    AtmReservation = 'AtmReservation'
}


export function ReservationTypeFromJSON(json: any): ReservationType {
    return ReservationTypeFromJSONTyped(json, false);
}

export function ReservationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationType {
    return json as ReservationType;
}

export function ReservationTypeToJSON(value?: ReservationType | null): any {
    return value as any;
}

