/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Status } from './Status';
import {
    StatusFromJSON,
    StatusFromJSONTyped,
    StatusToJSON,
} from './Status';

/**
 * 
 * @export
 * @interface SetReadStatusRequest
 */
export interface SetReadStatusRequest {
    /**
     * 
     * @type {Status}
     * @memberof SetReadStatusRequest
     */
    status: Status;
}

/**
 * Check if a given object implements the SetReadStatusRequest interface.
 */
export function instanceOfSetReadStatusRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function SetReadStatusRequestFromJSON(json: any): SetReadStatusRequest {
    return SetReadStatusRequestFromJSONTyped(json, false);
}

export function SetReadStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetReadStatusRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': StatusFromJSON(json['status']),
    };
}

export function SetReadStatusRequestToJSON(value?: SetReadStatusRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': StatusToJSON(value.status),
    };
}

