/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum StandingOrderFrequency {
    Other = 'Other',
    Weekly = 'Weekly',
    Biweekly = 'Biweekly',
    Semimonthly = 'Semimonthly',
    Monthly = 'Monthly',
    Bimonthly = 'Bimonthly',
    Quarterly = 'Quarterly',
    Yearly = 'Yearly',
    Daily = 'Daily'
}


export function StandingOrderFrequencyFromJSON(json: any): StandingOrderFrequency {
    return StandingOrderFrequencyFromJSONTyped(json, false);
}

export function StandingOrderFrequencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): StandingOrderFrequency {
    return json as StandingOrderFrequency;
}

export function StandingOrderFrequencyToJSON(value?: StandingOrderFrequency | null): any {
    return value as any;
}

