/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Beta API
 *
 * The version of the OpenAPI document: 2.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransferCreateRequest
 */
export interface TransferCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof TransferCreateRequest
     */
    fromAccountId: string;
    /**
     * 
     * @type {string}
     * @memberof TransferCreateRequest
     */
    toAccountId: string;
    /**
     * 
     * @type {string}
     * @memberof TransferCreateRequest
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof TransferCreateRequest
     */
    amount: number;
}

/**
 * Check if a given object implements the TransferCreateRequest interface.
 */
export function instanceOfTransferCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fromAccountId" in value;
    isInstance = isInstance && "toAccountId" in value;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "amount" in value;

    return isInstance;
}

export function TransferCreateRequestFromJSON(json: any): TransferCreateRequest {
    return TransferCreateRequestFromJSONTyped(json, false);
}

export function TransferCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fromAccountId': json['fromAccountId'],
        'toAccountId': json['toAccountId'],
        'message': json['message'],
        'amount': json['amount'],
    };
}

export function TransferCreateRequestToJSON(value?: TransferCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fromAccountId': value.fromAccountId,
        'toAccountId': value.toAccountId,
        'message': value.message,
        'amount': value.amount,
    };
}

