/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Authnetication API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenSuccess
 */
export interface TokenSuccess {
    /**
     * 
     * @type {string}
     * @memberof TokenSuccess
     */
    accessToken: string;
    /**
     * 
     * @type {number}
     * @memberof TokenSuccess
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof TokenSuccess
     */
    tokenType: TokenSuccessTokenTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TokenSuccess
     */
    scope: string;
}

/**
* @export
* @enum {string}
*/
export enum TokenSuccessTokenTypeEnum {
    Bearer = 'Bearer'
}


/**
 * Check if a given object implements the TokenSuccess interface.
 */
export function instanceOfTokenSuccess(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "expiresIn" in value;
    isInstance = isInstance && "tokenType" in value;
    isInstance = isInstance && "scope" in value;

    return isInstance;
}

export function TokenSuccessFromJSON(json: any): TokenSuccess {
    return TokenSuccessFromJSONTyped(json, false);
}

export function TokenSuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenSuccess {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'expiresIn': json['expires_in'],
        'tokenType': json['token_type'],
        'scope': json['scope'],
    };
}

export function TokenSuccessToJSON(value?: TokenSuccess | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'expires_in': value.expiresIn,
        'token_type': value.tokenType,
        'scope': value.scope,
    };
}

