/* tslint:disable */
/* eslint-disable */
/**
 * SBanken
 * SBanken Authnetication API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: rhuan@barreto.work
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenFailure
 */
export interface TokenFailure {
    /**
     * 
     * @type {string}
     * @memberof TokenFailure
     */
    error: string;
}

/**
 * Check if a given object implements the TokenFailure interface.
 */
export function instanceOfTokenFailure(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function TokenFailureFromJSON(json: any): TokenFailure {
    return TokenFailureFromJSONTyped(json, false);
}

export function TokenFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenFailure {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function TokenFailureToJSON(value?: TokenFailure | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': value.error,
    };
}

